### ISSUE TITLE
Question regarding consolidated.fasta

### ISSUE THREAD

**Issue by nbawe** [phac-nml/neptune#11]
Does consolidated.fasta includes all the sequences present in all the inclusion genomes?

How to determine that the found sequence is present and significant in all inclusion genomes?

Thanks

**Comment by emarinier** [comment]
> Does consolidated.fasta includes all the sequences present in all the inclusion genomes?

Yes. Please see [this link](https://phac-nml.github.io/neptune/output/) for more information.

> How to determine that the found sequence is present and significant in all inclusion genomes?

The signature score informs how discriminatory the signature is. Please see [this link](https://phac-nml.github.io/neptune/format/) for more information. The higher the inclusion score, the more the signature is represented in all the inclusion genomes. The closer the exclusion score is to zero, the more specific the signature is, with respect to the input data. The total score is the sum of the inclusion and exclusion scores.

**Comment by nbawe** [comment]
My problem is that consolidated.fasta no 1 sequence that is originating from first genome is not present in other genomes in sorted signatures.

Should the consolidated.fasta no 1 sequence be present with 100% similarity in all the other genomes in sorted signature fasta files?

**Comment by emarinier** [comment]
The signatures in the consolidated.fasta file will exactly match at least one inclusion genome (the genome it was taken from). They are not guaranteed to exactly match any other inclusion genome, but high-scoring signatures will very close match sequences in other inclusion genomes (for example, 95% sequence identity matches with the other inclusion genomes).

This strategy is desirable because mutation means that it's unlikely that two sequences will remain exactly the same, given enough time.

If you are looking for long sequences that exactly match with 100% similarity in many genomes (no errors, mutations, etc.), you might want to use an approach that finds the [longest common substring](https://en.wikipedia.org/wiki/Longest_common_substring_problem). A suffix tree approach may be helpful, but I don't know of any such tools.

**Comment by nbawe** [comment]
Thank you for quick explanation!
