### ISSUE TITLE
 [blastn] Query is Empty!

### ISSUE THREAD

**Issue by eppinglen** [phac-nml/neptune#7]
I am trying to use Neptune at the moment. However, I always getting the warning:  "[blastn] Query is Empty!"
I am running Neptune on draft assemblies and already used different k-mer sizes. Do you know a possible reason for this?

**Comment by emarinier** [comment]
One reason why this might be happening is because Neptune has not found any candidate signatures during the first pass.

It should be possible to verify if this is the case by looking inside the "candidates" directory in the output. If the FASTA files are empty in this directory, then that would explain why BLAST is giving a warning about the query being empty.

Whether or not there should be any (candidate) signatures would depend on the organization of inclusion and exclusion groups.

Let me know if the problem appears to be something else. Thanks!
